# Application
spring.application.name=${SPRING_APPLICATION_NAME}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

# Server
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}
spring.main.banner-mode=${SPRING_MAIN_BANNER_MODE}

# JWT
jwt.secret.key=${JWT_SECRET_KEY}

# Mail
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.protocol=${SPRING_MAIL_PROTOCOL}
spring.mail.properties.mail.smtp.from=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_FROM}
